-- =============================================================================
-- MotorSpecs core schema
--
-- Conventions
--   * Every table lives in `public` and has Row Level Security enabled
--     (policies are in 20260929000400_rls_policies.sql).
--   * Status-like columns are text + CHECK constraints so values can be added
--     later without enum migrations.
--   * Child rows that belong to a customer carry a denormalised `customer_id`
--     that is set by trigger from the parent row, never trusted from the client.
--   * `is_demo` marks seed/demo rows so they can be purged before go-live
--     (see supabase/scripts/purge_demo_data.sql).
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Reference sequences for human-readable numbers
-- -----------------------------------------------------------------------------
create sequence if not exists public.customer_code_seq start 10001;
create sequence if not exists public.vehicle_ref_seq start 24001;
create sequence if not exists public.inquiry_ref_seq start 5001;
create sequence if not exists public.sale_no_seq start 1001;

-- -----------------------------------------------------------------------------
-- Profiles: one row per auth user (staff and customers)
-- -----------------------------------------------------------------------------
create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  role text not null default 'customer' check (role in ('admin', 'sales', 'customer')),
  display_name text check (char_length(display_name) <= 120),
  email text,
  phone text check (char_length(phone) <= 40),
  locale text not null default 'en' check (locale in ('en', 'ja', 'ar')),
  -- The business owner. Cannot be demoted or deactivated from the app.
  is_owner boolean not null default false,
  is_active boolean not null default true,
  -- When true, staff privileges are only granted to sessions that completed
  -- authenticator-app MFA (JWT aal = 'aal2'). See public.is_staff().
  mfa_required boolean not null default false,
  is_demo boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index profiles_email_key on public.profiles (lower(email));

-- -----------------------------------------------------------------------------
-- Lookups
-- -----------------------------------------------------------------------------
create table public.makes (
  id smallint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique check (slug ~ '^[a-z0-9-]+$'),
  sort_order smallint not null default 100
);

create table public.models (
  id integer generated by default as identity primary key,
  make_id smallint not null references public.makes (id) on delete restrict,
  name text not null,
  slug text not null check (slug ~ '^[a-z0-9-]+$'),
  unique (make_id, slug)
);

create table public.body_types (
  code text primary key check (code ~ '^[a-z_]+$'),
  sort_order smallint not null default 100
);

create table public.locations (
  id smallint generated by default as identity primary key,
  name text not null unique,
  country_code char(2) not null default 'JP',
  port text
);

create table public.features (
  code text primary key check (code ~ '^[a-z0-9_]+$'),
  category text not null check (category in ('comfort', 'safety', 'exterior', 'interior', 'audio', 'utility')),
  sort_order smallint not null default 100
);

-- -----------------------------------------------------------------------------
-- Customers: the master customer database.
-- A row may exist before the person signs up (created by staff). It is linked to
-- a login (auth_user_id) only through a verified invite code.
-- -----------------------------------------------------------------------------
create table public.customers (
  id uuid primary key default gen_random_uuid(),
  customer_code text not null unique
    default ('MSC-' || nextval('public.customer_code_seq')::text),
  auth_user_id uuid unique references auth.users (id) on delete set null,
  status text not null default 'active' check (status in ('lead', 'active', 'inactive', 'merged')),
  merged_into uuid references public.customers (id),

  -- Customer-editable profile fields
  full_name text not null check (char_length(full_name) between 1 and 160),
  company_name text check (char_length(company_name) <= 160),
  phone text check (char_length(phone) <= 40),
  whatsapp text check (char_length(whatsapp) <= 40),
  country_code char(2),
  city text check (char_length(city) <= 120),
  address_line text check (char_length(address_line) <= 300),
  postal_code text check (char_length(postal_code) <= 20),
  destination_port text check (char_length(destination_port) <= 120),
  preferred_language text not null default 'en' check (preferred_language in ('en', 'ja', 'ar')),
  preferred_contact text not null default 'email' check (preferred_contact in ('email', 'phone', 'whatsapp')),

  -- Admin-controlled fields (read-only to customers, enforced by trigger)
  email text check (char_length(email) <= 254),
  verification_status text not null default 'unverified'
    check (verification_status in ('unverified', 'pending', 'verified', 'rejected')),
  verified_name text,
  verified_company text,
  verified_at timestamptz,
  verified_by uuid references public.profiles (id),
  assigned_staff_id uuid references public.profiles (id),
  source text not null default 'website' check (source in ('website', 'staff', 'import', 'referral')),
  tags text[] not null default '{}',

  is_demo boolean not null default false,
  created_by uuid references public.profiles (id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index customers_assigned_idx on public.customers (assigned_staff_id);
create index customers_email_idx on public.customers (lower(email));
create index customers_phone_idx on public.customers (phone);

-- Full history of who owned the customer relationship.
create table public.customer_assignments (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references public.customers (id) on delete cascade,
  from_staff_id uuid references public.profiles (id),
  to_staff_id uuid references public.profiles (id),
  assigned_by uuid references public.profiles (id),
  reason text check (char_length(reason) <= 500),
  created_at timestamptz not null default now()
);

create index customer_assignments_customer_idx on public.customer_assignments (customer_id, created_at desc);

-- One-time codes that let a registered user claim a staff-created record.
-- Only the SHA-256 hash of the code is stored.
create table public.customer_invites (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references public.customers (id) on delete cascade,
  code_hash text not null unique,
  code_hint text not null,
  expires_at timestamptz not null default now() + interval '14 days',
  used_at timestamptz,
  used_by uuid references auth.users (id),
  revoked_at timestamptz,
  created_by uuid references public.profiles (id),
  created_at timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- Vehicles
-- -----------------------------------------------------------------------------
create table public.vehicles (
  id uuid primary key default gen_random_uuid(),

  -- Identity
  ref_no text not null unique default ('MS' || nextval('public.vehicle_ref_seq')::text)
    check (ref_no ~ '^[A-Za-z0-9-]{2,30}$'),
  slug text not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  chassis_no text check (char_length(chassis_no) <= 40),
  model_code text check (char_length(model_code) <= 40),
  engine_code text check (char_length(engine_code) <= 40),
  condition_grade text check (char_length(condition_grade) <= 10),
  auction_sheet_ref text check (char_length(auction_sheet_ref) <= 80),

  -- Classification
  make_id smallint references public.makes (id),
  model_id integer references public.models (id),
  body_type text references public.body_types (code),
  location_id smallint references public.locations (id),
  reg_year smallint check (reg_year between 1950 and 2100),
  reg_month smallint check (reg_month between 1 and 12),
  manufacture_year smallint check (manufacture_year between 1950 and 2100),
  grade text check (char_length(grade) <= 120),

  -- Specifications
  mileage_km integer check (mileage_km >= 0),
  operating_hours integer check (operating_hours >= 0),
  engine_cc integer check (engine_cc between 0 and 30000),
  transmission text check (transmission in ('AT', 'MT', 'CVT', 'AMT', 'other')),
  fuel text check (fuel in ('petrol', 'diesel', 'hybrid', 'plugin_hybrid', 'electric', 'lpg', 'other')),
  drive text check (drive in ('2WD', '4WD', 'AWD')),
  steering text check (steering in ('RHD', 'LHD')),
  exterior_color text check (char_length(exterior_color) <= 60),
  interior_color text check (char_length(interior_color) <= 60),
  doors smallint check (doors between 0 and 8),
  seats smallint check (seats between 0 and 60),
  has_360_view boolean not null default false,

  -- Customs / shipping information
  length_mm integer check (length_mm between 0 and 30000),
  width_mm integer check (width_mm between 0 and 5000),
  height_mm integer check (height_mm between 0 and 6000),
  m3 numeric(7, 2) check (m3 >= 0),
  weight_kg integer check (weight_kg >= 0),
  gross_weight_kg integer check (gross_weight_kg >= 0),
  max_load_kg integer check (max_load_kg >= 0),
  tyre_front text check (char_length(tyre_front) <= 40),
  tyre_rear text check (char_length(tyre_rear) <= 40),

  -- Public pricing. `ask` = "Ask for price": the amount is never exposed.
  price_visibility text not null default 'ask' check (price_visibility in ('public', 'ask')),
  fob_price_usd numeric(12, 2) check (fob_price_usd > 0),
  previous_price_usd numeric(12, 2) check (previous_price_usd > 0),

  -- Publishing
  status text not null default 'draft' check (status in ('draft', 'published', 'reserved', 'sold', 'archived')),
  is_featured boolean not null default false,
  published_at timestamptz,

  is_demo boolean not null default false,
  created_by uuid references public.profiles (id),
  updated_by uuid references public.profiles (id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint vehicles_public_price_requires_amount
    check (price_visibility = 'ask' or fob_price_usd is not null)
);

create index vehicles_status_idx on public.vehicles (status, published_at desc);
create index vehicles_make_model_idx on public.vehicles (make_id, model_id);

-- Private information that must never reach the public site or customers.
create table public.vehicle_private (
  vehicle_id uuid primary key references public.vehicles (id) on delete cascade,
  internal_cost_jpy numeric(14, 0) check (internal_cost_jpy >= 0),
  internal_cost_usd numeric(12, 2) check (internal_cost_usd >= 0),
  supplier text check (char_length(supplier) <= 160),
  auction_house text check (char_length(auction_house) <= 160),
  purchase_date date,
  internal_notes text check (char_length(internal_notes) <= 5000),
  updated_by uuid references public.profiles (id),
  updated_at timestamptz not null default now()
);

create table public.vehicle_translations (
  vehicle_id uuid not null references public.vehicles (id) on delete cascade,
  locale text not null check (locale in ('en', 'ja', 'ar')),
  title text check (char_length(title) <= 200),
  description text check (char_length(description) <= 10000),
  remarks text check (char_length(remarks) <= 4000),
  updated_at timestamptz not null default now(),
  primary key (vehicle_id, locale)
);

create table public.vehicle_features (
  vehicle_id uuid not null references public.vehicles (id) on delete cascade,
  feature_code text not null references public.features (code) on delete cascade,
  primary key (vehicle_id, feature_code)
);

create table public.vehicle_media (
  id uuid primary key default gen_random_uuid(),
  vehicle_id uuid not null references public.vehicles (id) on delete cascade,
  kind text not null default 'photo'
    check (kind in ('photo', 'inspection_sheet', 'auction_sheet', 'view360', 'video', 'other')),
  -- Public media live in the public `vehicle-photos` bucket; private media in
  -- the staff-only `vehicle-internal` bucket.
  bucket text not null default 'vehicle-photos' check (bucket in ('vehicle-photos', 'vehicle-internal')),
  storage_path text not null check (char_length(storage_path) <= 500),
  is_public boolean not null default true,
  sort_order smallint not null default 0,
  caption text check (char_length(caption) <= 200),
  mime_type text,
  size_bytes integer check (size_bytes between 0 and 10485760),
  created_by uuid references public.profiles (id),
  created_at timestamptz not null default now(),
  unique (bucket, storage_path),
  constraint vehicle_media_bucket_matches_visibility
    check ((is_public and bucket = 'vehicle-photos') or (not is_public and bucket = 'vehicle-internal'))
);

create index vehicle_media_vehicle_idx on public.vehicle_media (vehicle_id, sort_order);

create table public.vehicle_price_history (
  id uuid primary key default gen_random_uuid(),
  vehicle_id uuid not null references public.vehicles (id) on delete cascade,
  old_price_usd numeric(12, 2),
  new_price_usd numeric(12, 2),
  old_visibility text,
  new_visibility text,
  changed_by uuid references public.profiles (id),
  changed_at timestamptz not null default now()
);

create table public.vehicle_status_history (
  id uuid primary key default gen_random_uuid(),
  vehicle_id uuid not null references public.vehicles (id) on delete cascade,
  from_status text,
  to_status text not null,
  changed_by uuid references public.profiles (id),
  changed_at timestamptz not null default now()
);

create table public.favorites (
  customer_id uuid not null references public.customers (id) on delete cascade,
  vehicle_id uuid not null references public.vehicles (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (customer_id, vehicle_id)
);

-- -----------------------------------------------------------------------------
-- Deals: inquiries -> messages / notes / offers -> reservations -> sales
-- -----------------------------------------------------------------------------
create table public.inquiries (
  id uuid primary key default gen_random_uuid(),
  ref_no text not null unique default ('INQ-' || nextval('public.inquiry_ref_seq')::text),
  customer_id uuid not null references public.customers (id),
  vehicle_id uuid references public.vehicles (id),
  kind text not null default 'inquiry' check (kind in ('inquiry', 'offer')),
  subject text not null check (char_length(subject) between 1 and 200),
  status text not null default 'new'
    check (status in ('new', 'open', 'quoted', 'negotiating', 'reserved', 'won', 'lost', 'closed')),
  destination_port text check (char_length(destination_port) <= 120),
  follow_up_at timestamptz,
  last_message_at timestamptz not null default now(),
  closed_reason text check (char_length(closed_reason) <= 500),
  is_demo boolean not null default false,
  created_by uuid references public.profiles (id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index inquiries_customer_idx on public.inquiries (customer_id, last_message_at desc);
create index inquiries_status_idx on public.inquiries (status, last_message_at desc);

create table public.messages (
  id uuid primary key default gen_random_uuid(),
  inquiry_id uuid not null references public.inquiries (id) on delete cascade,
  customer_id uuid not null references public.customers (id),
  sender_id uuid references public.profiles (id),
  sender_role text not null check (sender_role in ('admin', 'sales', 'customer', 'system')),
  body text not null check (char_length(body) between 1 and 5000),
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index messages_inquiry_idx on public.messages (inquiry_id, created_at);

-- Staff-only notes. Kept in a separate table so they can never leak through a
-- customer's message policy.
create table public.internal_notes (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references public.customers (id),
  inquiry_id uuid references public.inquiries (id) on delete cascade,
  author_id uuid references public.profiles (id),
  body text not null check (char_length(body) between 1 and 5000),
  created_at timestamptz not null default now()
);

create index internal_notes_customer_idx on public.internal_notes (customer_id, created_at desc);

create table public.offers (
  id uuid primary key default gen_random_uuid(),
  inquiry_id uuid not null references public.inquiries (id) on delete cascade,
  customer_id uuid not null references public.customers (id),
  vehicle_id uuid references public.vehicles (id),
  kind text not null check (kind in ('customer_offer', 'counter_offer', 'quotation')),
  amount_usd numeric(12, 2) not null check (amount_usd > 0 and amount_usd < 10000000),
  incoterm text not null default 'FOB' check (incoterm in ('FOB', 'CFR', 'CIF')),
  freight_usd numeric(12, 2) check (freight_usd >= 0),
  insurance_usd numeric(12, 2) check (insurance_usd >= 0),
  inspection_usd numeric(12, 2) check (inspection_usd >= 0),
  destination_port text check (char_length(destination_port) <= 120),
  valid_until date,
  message text check (char_length(message) <= 2000),
  status text not null default 'pending'
    check (status in ('pending', 'accepted', 'declined', 'withdrawn', 'expired', 'superseded')),
  responded_at timestamptz,
  responded_by uuid references public.profiles (id),
  created_by uuid references public.profiles (id),
  created_at timestamptz not null default now()
);

create index offers_inquiry_idx on public.offers (inquiry_id, created_at);

create table public.reservations (
  id uuid primary key default gen_random_uuid(),
  vehicle_id uuid not null references public.vehicles (id),
  customer_id uuid not null references public.customers (id),
  inquiry_id uuid references public.inquiries (id),
  offer_id uuid references public.offers (id),
  status text not null default 'active' check (status in ('active', 'released', 'expired', 'converted')),
  agreed_price_usd numeric(12, 2) check (agreed_price_usd > 0),
  reserved_until timestamptz not null default now() + interval '5 days',
  notes text check (char_length(notes) <= 2000),
  released_at timestamptz,
  release_reason text check (char_length(release_reason) <= 500),
  is_demo boolean not null default false,
  reserved_by uuid references public.profiles (id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- A vehicle can only have one active reservation at a time.
create unique index reservations_one_active_per_vehicle
  on public.reservations (vehicle_id) where status = 'active';
create index reservations_customer_idx on public.reservations (customer_id);

create table public.sales (
  id uuid primary key default gen_random_uuid(),
  sale_no text not null unique
    default ('SO-' || to_char(now(), 'YYYY') || '-' || nextval('public.sale_no_seq')::text),
  vehicle_id uuid not null references public.vehicles (id),
  customer_id uuid not null references public.customers (id),
  reservation_id uuid references public.reservations (id),
  inquiry_id uuid references public.inquiries (id),
  staff_id uuid references public.profiles (id),
  incoterm text not null default 'FOB' check (incoterm in ('FOB', 'CFR', 'CIF')),
  price_usd numeric(12, 2) not null check (price_usd > 0),
  freight_usd numeric(12, 2) not null default 0 check (freight_usd >= 0),
  insurance_usd numeric(12, 2) not null default 0 check (insurance_usd >= 0),
  other_charges_usd numeric(12, 2) not null default 0 check (other_charges_usd >= 0),
  total_usd numeric(12, 2) generated always as (price_usd + freight_usd + insurance_usd + other_charges_usd) stored,
  status text not null default 'awaiting_payment'
    check (status in ('awaiting_payment', 'partially_paid', 'paid', 'shipping', 'delivered', 'completed', 'cancelled')),
  invoice_no text unique,
  notes text check (char_length(notes) <= 2000),
  sold_at timestamptz not null default now(),
  completed_at timestamptz,
  cancelled_at timestamptz,
  cancel_reason text check (char_length(cancel_reason) <= 500),
  is_demo boolean not null default false,
  created_by uuid references public.profiles (id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- A vehicle can only be sold once (unless the sale is cancelled).
create unique index sales_one_per_vehicle
  on public.sales (vehicle_id) where status <> 'cancelled';
create index sales_customer_idx on public.sales (customer_id);

create table public.payments (
  id uuid primary key default gen_random_uuid(),
  sale_id uuid not null references public.sales (id),
  customer_id uuid not null references public.customers (id),
  amount_usd numeric(12, 2) not null check (amount_usd > 0),
  method text not null default 'bank_transfer' check (method in ('bank_transfer', 'card', 'cash', 'other')),
  reference text check (char_length(reference) <= 120),
  paid_on date not null default current_date,
  -- recorded (by sales) -> verified (by admin) | void (by admin). Never deleted.
  status text not null default 'recorded' check (status in ('recorded', 'verified', 'void')),
  note text check (char_length(note) <= 1000),
  recorded_by uuid references public.profiles (id),
  verified_by uuid references public.profiles (id),
  verified_at timestamptz,
  void_reason text check (char_length(void_reason) <= 500),
  is_demo boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index payments_sale_idx on public.payments (sale_id);

create table public.shipments (
  id uuid primary key default gen_random_uuid(),
  sale_id uuid not null unique references public.sales (id),
  customer_id uuid not null references public.customers (id),
  status text not null default 'awaiting_booking'
    check (status in ('awaiting_booking', 'booked', 'at_port', 'in_transit', 'arrived', 'released')),
  method text check (method in ('roro', 'container')),
  vessel_name text check (char_length(vessel_name) <= 120),
  voyage_no text check (char_length(voyage_no) <= 40),
  port_of_loading text check (char_length(port_of_loading) <= 120),
  port_of_discharge text check (char_length(port_of_discharge) <= 120),
  etd date,
  eta date,
  bl_number text check (char_length(bl_number) <= 60),
  container_no text check (char_length(container_no) <= 40),
  updated_by uuid references public.profiles (id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.shipment_events (
  id uuid primary key default gen_random_uuid(),
  shipment_id uuid not null references public.shipments (id) on delete cascade,
  customer_id uuid not null references public.customers (id),
  status text not null,
  note text check (char_length(note) <= 1000),
  visible_to_customer boolean not null default true,
  created_by uuid references public.profiles (id),
  created_at timestamptz not null default now()
);

create index shipment_events_shipment_idx on public.shipment_events (shipment_id, created_at);

-- Customer-specific files in the private `customer-documents` bucket.
-- Object path convention: {customer_id}/{document_id}/{file_name}
create table public.documents (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references public.customers (id),
  sale_id uuid references public.sales (id),
  inquiry_id uuid references public.inquiries (id),
  kind text not null default 'other' check (kind in (
    'quotation', 'proforma_invoice', 'invoice', 'receipt', 'export_certificate',
    'deregistration', 'bill_of_lading', 'inspection', 'shipping', 'other')),
  title text not null check (char_length(title) between 1 and 200),
  storage_path text not null unique check (char_length(storage_path) <= 500),
  file_name text not null check (char_length(file_name) <= 200),
  mime_type text not null check (mime_type in ('application/pdf', 'image/jpeg', 'image/png', 'image/webp')),
  size_bytes integer not null check (size_bytes between 1 and 10485760),
  shared_with_customer boolean not null default false,
  shared_at timestamptz,
  deleted_at timestamptz,
  is_demo boolean not null default false,
  uploaded_by uuid references public.profiles (id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index documents_customer_idx on public.documents (customer_id, created_at desc);

create table public.tasks (
  id uuid primary key default gen_random_uuid(),
  title text not null check (char_length(title) between 1 and 200),
  notes text check (char_length(notes) <= 2000),
  customer_id uuid references public.customers (id),
  inquiry_id uuid references public.inquiries (id) on delete cascade,
  assigned_to uuid not null references public.profiles (id),
  due_at timestamptz not null,
  priority text not null default 'normal' check (priority in ('low', 'normal', 'high')),
  status text not null default 'open' check (status in ('open', 'done', 'cancelled')),
  completed_at timestamptz,
  is_demo boolean not null default false,
  created_by uuid references public.profiles (id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index tasks_assignee_idx on public.tasks (assigned_to, status, due_at);

-- -----------------------------------------------------------------------------
-- Activity trail. Append-only: written only by SECURITY DEFINER triggers and
-- functions. No role is granted INSERT/UPDATE/DELETE through RLS.
-- -----------------------------------------------------------------------------
create table public.activity_log (
  id bigint generated always as identity primary key,
  occurred_at timestamptz not null default now(),
  actor_id uuid,
  actor_role text,
  action text not null,
  entity_type text not null,
  entity_id text,
  customer_id uuid,
  summary text,
  details jsonb not null default '{}'::jsonb
);

create index activity_log_customer_idx on public.activity_log (customer_id, occurred_at desc);
create index activity_log_entity_idx on public.activity_log (entity_type, entity_id);
create index activity_log_time_idx on public.activity_log (occurred_at desc);
